name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      run: |
        sudo apt-get install -y curl wget software-properties-common apt-transport-https ca-certificates gnupg2
        sudo curl -sL https://deb.nodesource.com/setup_18.x | sudo bash -
    - name: Build
      run: |
        gofmt -w -s . && git diff --exit-code
        make cover
